# Generated by Django 5.2.5 on 2026-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_leadcapture_initial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
