# Generated by Django 5.2.5 on 2026-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('IMG', 'IMG'), ('XLS', 'XLS')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
