# Generated by Django 5.2.13 on 2026-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
